services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: took5678%^&*
      MYSQL_DATABASE: took
      MYSQL_USER: turtle
      MYSQL_PASSWORD: took5678%^&*
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  springboot:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "81:80"
  #     - "444:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - springboot
