version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/jenkins_home:/var/jenkins_home

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: took5678%^&*
      MYSQL_DATABASE: took
      MYSQL_USER: turtle
      MYSQL_PASSWORD: took5678%^&*
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  springboot:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - springboot
